improve error handling

diff --git a/dt b/dt
--- a/dt
+++ b/dt
@@ -11,13 +11,19 @@ set -e
 function arg() {
     case $2 in
         uint)
-            if [[ ! $3 =~ ^[0-9]+$ ]]
+            if [[ $3 =~ ^[0-9]+$ ]]
             then
-                echo "argument <$1> does not match pattern $2"
-                exit
+                return
             fi
             ;;
+        *)
+            echo "internal error: unknown pattern <$2>"
+            exit
+            ;;
     esac
+
+    echo "argument <$1>: \"$3\" does not match pattern $2"
+    exit 1
 }
 
 function cmd_none() {
